refactor: improvement of http calls and baseUrl
ServeRest/front pull request #29
Opened 2021-08-10 17:25 UTC by maximilianoalves

2021-08-10 17:34 UTC, PauloGoncalvesBH commented on src/services/login.js
> +    password: password,
```suggestion
    email,
    password,
```
É apenas questão estética, não é preciso alterar, se quiser pode seguir em frente mesmo com essa sugestão.

2021-08-10 18:09 UTC, PauloGoncalvesBH requested changes

2021-08-10 18:09 UTC, PauloGoncalvesBH commented on src/views/admin/registerProducts.js
> +      registerProduct(this.state.name, this.state.price, this.state.description, this.state.quantity,)
```suggestion
      registerProduct(this.state)
```
Como `this.state` é um objeto e já possui `name`, `price`, `description` e `quantity`, acredito que assim irá funcionar. Só não deve funcionar se tiver mais alguma propriedade além das listadas.
**Vai ser preciso fazer esse mesmo ajuste em todos os locais que chamam `registerProduct`.**

Caso a sugestão acima não funcione, tente a seguinte:

```suggestion
      registerProduct({ 
        name: this.state.name,
        price: this.state.price,
        description: this.state.description,
        quantity: this.state.quantity
      })
```

_Obsv.: Não sei se a indentação está correta, vai ser preciso verificar na IDE._

2021-08-10 18:09 UTC, PauloGoncalvesBH commented on src/services/products.js
> +export async function registerProductWithImage(name, price, description, quantity, image) {
```suggestion
export async function registerProductWithImage({ name, price, description, quantity, image }) {
```
Fazer o mesmo ajuste sugerido em `registerProduct`. É preciso alterar a forma que é consumido conforme sugeri em outro review.

2021-08-10 18:09 UTC, PauloGoncalvesBH commented on src/services/users.js
> +export async function registerUser(name, email, password, administrador) {
```suggestion
export async function registerUser({ name, email, password, administrador }) {
```
Fazer o mesmo ajuste fornecido no review do `registerProduct`.

2021-08-10 18:09 UTC, PauloGoncalvesBH commented on src/services/products.js
> +    }
```suggestion
    const config = {
        headers: {
            'Access-Control-Allow-Origin': '*',
            Accept: 'application/json',
            Authorization: localStorage.getItem('serverest/userToken'),
        },
    }
```

É preciso ajustar a indentação.

2021-08-10 18:09 UTC, PauloGoncalvesBH commented on src/views/login.js
> +// import Utils from '../services/utils'
Esse código comentado, não faz sentido remover todo ele?

2021-08-10 18:11 UTC, PauloGoncalvesBH commented
@maximilianoalves fiz algumas sugestões de alteração. Elas são focadas em tornar o código mais legível e com melhor manutenção (alterar os argumentos para objeto, por exemplo).
Qualquer dúvida só falar, podemos discutir os reviews se necessários.

2021-08-10 21:23 UTC, PauloGoncalvesBH requested changes

2021-08-10 21:23 UTC, PauloGoncalvesBH commented on src/services/products.js
> +export async function registerProduct(state) {
```suggestion
export async function registerProduct({ name, price, description, quantity }) {
```
Acredito que assim fica mais claro sobre o que deve receber. Ao chamar o método `registerProduct` será claro que precisa ter nome, preço, descrição e quantidade, mais próximo da realidade. Enquanto _state_ não é exatamente o que esse método precisa, mas sim o nome, preço, etc, que ele contém.

O que acha dessa sugestão?

Caso concorde será preciso ajustar esse método, o `registerUser` e `registerProductWithImage`, bem como os locais que os consomem.

Caso tenha dúvidas sobre como implementar posso fazer o ajuste aqui.

2021-08-10 21:57 UTC, maximilianoalves commented on src/services/products.js
> +export async function registerProduct(state) {
Pode fazer a alteração? Acho que não entendi, pois talvez não sabia como fazer.

2021-08-11 01:28 UTC, PauloGoncalvesBH commented on src/services/products.js
> +export async function registerProduct(state) {
Fiz a alteração, consegue revisar?

2021-08-11 12:02 UTC, merged